<?php
// Text
$_['text_refine']           = 'Уточнить поиск';
$_['text_product']          = 'Товары';
$_['text_error']            = 'Категория не найдена!';
$_['text_empty']            = 'В этой категории нет товаров.';
$_['text_quantity']         = 'Кол-во:';
$_['text_manufacturer']     = 'Производитель:';
$_['text_model']            = 'Код товара:';
$_['text_points']           = 'Бонусные баллы:';
$_['text_price']            = 'Цена:';
$_['text_tax']              = 'Без налога:';
$_['text_compare']          = 'Сравнение товаров (%s)';
$_['text_sort']             = 'Сортировать:';
$_['text_default']          = 'По умолчанию';
$_['text_name_asc']         = 'По имени (A - Я)';
$_['text_name_desc']        = 'По имени (Я - A)';
$_['text_price_asc']        = 'По цене (возрастанию)';
$_['text_price_desc']       = 'По цене (убыванию)';
$_['text_rating_asc']       = 'По рейтингу (возрастанию)';
$_['text_rating_desc']      = 'По рейтингу (убыванию)';
$_['text_model_asc']        = 'По модели (A - Я)';
$_['text_model_desc']       = 'По модели (Я - A)';
$_['text_limit']            = 'Показывать:';
$_['text_selected_filter']  = 'Выбранные фильтры';

$_['text_no_products']      = 'Нет товаров.';
$_['text_read_completely']  = 'Читать полностью';
$_['text_useful_links']     = 'Полезные ссылки';
$_['text_specify_category'] = 'Уточните категорию:';
$_['text_specify_brand']	= 'Уточните бренд:';
$_['text_items_found']  	= 'Найдено товаров:';
$_['text_result_by_query']	= 'Результаты поиска по запросу';
$_['text_gift']				= '+ подарок';
$_['text_buy']				= 'Купить';
$_['text_by_category']		= 'По категориям';
$_['text_by_type']			= 'По типу';
$_['text_special_offers']	= 'Специальные предложения';
$_['text_category']			= 'Категория';